#!/bin/bash
#PBS -q checkpt
# the queue to be used. 
#
#PBS -A loni_ngchc_2012
#
#PBS -l nodes=1:ppn=8
# number of nodes and number of processors on each node to be used.
# Do NOT use ppn = 1. Note that there are 8 processors on each Queen Bee node.
#
#PBS -l cput=00:30:00
# requested CPU time.
#
#PBS -l walltime=00:30:00
# requested Wall-clock time.
#
#PBS -o cjlog
# name of the standard out file to be "output-file".
#
#PBS -j oe
# standard error output merge to the standard output file.
#
#PBS -N swan_b02
# name of the job (that will appear on executing the qstat command).
#
# Following are non PBS commands. PLEASE ADOPT THE SAME EXECUTION SCHEME
# i.e. execute the job by copying the necessary files from your home directpory
# to the scratch space, execute in the scratch space, and copy back
# the necessary files to your home directory.
#
export WORK_DIR=/work/klhu/swan_tutorial/2_ISAAC
cd $WORK_DIR
# changing to your working directory (we recommend you to use work volume for batch job run)
#
export NPROCS=`wc -l $PBS_NODEFILE |gawk '//{print $1}'`
# REQUIRED for PBS to work.
#
date
#timing the time job starts
#

# For MVAPICH2 jobs, start the mpd daemon on each allocated node.
export MPDSNP=`uniq $PBS_NODEFILE |wc -l| cut -d'/' -f1`
cat $PBS_NODEFILE | uniq > $WORK_DIR/mpd_nodefile_$USER
export MPD_NODEFILE=$WORK_DIR/mpd_nodefile_$USER
mpdboot -v -n $MPDSNP -f $MPD_NODEFILE
mpdtrace -l
rm $MPD_NODEFILE
# run mvapich2 jobs
mpirun -np $NPROCS $WORK_DIR/swan_mpi >output
# stop mpd daemons
mpdallexit

date
# timing your job

