FROM ubuntu

RUN apt-get update 
RUN apt-get install -y g++ make python3-pip python3 wget git make nodejs npm curl jq sshpass
RUN pip3 install --upgrade pip
RUN pip3 install jupyter jupyterhub matplotlib numpy notebook
RUN npm install -g configurable-http-proxy
RUN apt-get install -y vim
RUN useradd -m jupuser
USER jupuser
RUN pip3 install ipywidgets
RUN jupyter nbextension enable --py widgetsnbextension
RUN pip3 install setvar --user
WORKDIR /home/jupuser
RUN git clone https://github.com/ysboss/agave-model.git
WORKDIR /home/jupuser/agave-model

# Horrible hack to get the URL to display properly
USER root
RUN perl -p -i -e 's/0\.0\.0\.0/1.1.1.1/' /usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py
USER jupuser

CMD jupyter notebook --ip 0.0.0.0 --no-browser --port 8003
