from setvar import *
setvar("""
MACHINE_NAME=shelob
DOMAIN=hpc.lsu.edu
EMAIL=sbrandt@cct.lsu.edu
AGAVE_USERNAME=stevenrbrandt
MACHINE_USERNAME=sbrandt
PORT=22
ALLOCATION=hpc_tutorials
AGAVE_JOB_MAX_RUNTIME=00:15:00
AGAVE_JOB_BATCH_QUEUE=checkpt
AGAVE_JOB_NODE_COUNT=1
AGAVE_PROCS_PER_NODE=1

DOCKERHUB_NAME=stevenrbrandt
WORK_DIR=/home/${MACHINE_USERNAME}
HOME_DIR=/home/${MACHINE_USERNAME}
SCRATCH_DIR=/home/${MACHINE_USERNAME}
DEPLOYMENT_PATH=agave-deployment
AGAVE_JSON_PARSER=jq

APP_NAME=funwave-tvd-${MACHINE_NAME}-${AGAVE_USERNAME}
STORAGE_MACHINE=${MACHINE_NAME}-storage-${AGAVE_USERNAME}
EXEC_MACHINE=${MACHINE_NAME}-exec-${AGAVE_USERNAME}
""")
