#!/usr/bin/env python3

# This is the launcher to be used by mpich
# to run jobs on remote notes.

from subprocess import *
import sys
import os
import re
image = os.environ["SINGULARITY_CONTAINER"]
host = sys.argv[1:2]
if host == ["-x"]:
    host = sys.argv[2:3]
    cmd = sys.argv[3:]
else:
    cmd = sys.argv[2:]

full_cmd = ["ssh"] + host + ["singularity","exec"] + [image] + cmd

call(full_cmd) 
